-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-06-29T13:15:14.863Z
CREATE TABLE "entries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" text NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "updated_at" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "analyses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entry_id" integer NOT NULL,
  "user_id" text NOT NULL,
  "emotion" text,
  "themes" text,
  "patterns" text,
  "positive_points" text,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "summaries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" text NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "summary_content" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "updated_at" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE INDEX ON "entries" ("user_id", "created_at");

CREATE INDEX ON "analyses" ("user_id", "created_at");

CREATE UNIQUE INDEX ON "summaries" ("user_id", "start_date", "end_date");

ALTER TABLE "analyses" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;
